language: go

go:
  - 1.5

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
