language: go

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - go get ./...
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - make test
  - make bench

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
